site_name: BBBase Docs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
