site_name: BBBase Docs
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
theme:
  name: material
  features:
    - navigation.tabs
    - toc.follow
    - content.code.copy
      #  palette: 
      #    primary: orange
    # Palette toggle for light mode
    #   - scheme: default
    #     toggle:
    #       icon: material/brightness-7 
    #       name: Switch to dark mode

    #   # Palette toggle for dark mode
    #   - scheme: slate
    #     toggle:
    #       icon: material/brightness-4
    #       name: Switch to light mode
